# Generated by Django 4.1.2 on 2022-12-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_extenduser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
