# Generated by Django 4.1.2 on 2022-10-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=120)),
                ('creation_date', models.DateField()),
                ('owner_first_name', models.CharField(max_length=16)),
                ('owner_last_name', models.CharField(max_length=16)),
                ('collaborators', models.IntegerField()),
            ],
        ),
    ]
